### ISSUE TITLE
README.mdにgithub.ioのページへのリンクを貼る

### ISSUE THREAD

**Issue by gogotea55t** [piesmist/bbp-original-db-front#1]
Githubのリポジトリのトップページに行くと、README.mdというファイルの中身が表示されています。ここに、github.ioへのページのリンクを貼ってください。

* mdファイルは[markdown](https://help.github.com/ja/github/writing-on-github/basic-writing-and-formatting-syntax)という言語で書かれているので、書き方も併せて調べましょう。書き方をちゃんと調べないと、リンクは貼れないと思われます。
* あわせて「やりたいこと」も書いておくといいかもしれません。
* できたらこの下の欄にその旨コメント書いてください。

**Comment by piesmist** [comment]
やりました。

**Comment by gogotea55t** [comment]
あ～Github.ioへのリンクってhttps://piesmist.github.io/bbp-original-db-front/
のつもりでした。まあでもMarkdownは書けてるのでOKですね。

**Comment by piesmist** [comment]
あ～なるほどっす！
てかこのページのinfo的な立ち位置なんすねこれ！今からまとめようかと

**Comment by gogotea55t** [comment]
そうですね～開発者向けのinfoページって感じですね。

**Comment by gogotea55t** [comment]
Readmeバッチリ整備されたのでクローズします。
