### ISSUE TITLE
一番上にタイトルを表示させる

### ISSUE THREAD

**Issue by gogotea55t** [piesmist/bbp-original-db-front#2]
Webページの一番上にタイトルを載せてください。どういうタイトルにするのかはお任せします。HTMLの見出しタグを使うといいと思います。

なお、ファイルを編集するにあたっては、masterブランチに直接pushしないようにしてください。
1. ブランチを作る
2. チェックアウトする
3. チェックアウトしたブランチにcommitしてpushする
4. pushしたブランチからmasterにpull requestsを出す
という流れで作業してください。
（最初にやったチュートリアルを思い出して！）

4が終わったらその旨この下にコメントを書いてください。

**Comment by gogotea55t** [comment]
pull requestを出すときにpull requestの名前を設定することになるのですが、その名前は「fixed #2」にするとよいです。（pull requestが承認されてmasterにマージされると、このIssueが自動的にクローズされるので）

**Comment by piesmist** [comment]
なんかできてました。
この辺ムズそうなので今度教えてくれると助かります。
