### ISSUE TITLE
楽曲の登録数をタイトルの下に表示させる

### ISSUE THREAD

**Issue by gogotea55t** [piesmist/bbp-original-db-front#3]
csvファイル（≒このWebページ）に何曲登録されているのかを、タイトルの下に表示してみましょう。
```
登録曲数：ＸＸＸ曲
```
のようなイメージです。
musicListの要素数を数えるといいのではないかと思います。
タイトルの下に表示するのが難しければ、まずは`console.log()`で表示するところまででもOKです。

**Comment by piesmist** [comment]
おそらく想定した形ではなかったと思いますが実装しました！
