### ISSUE TITLE
BootstrapのTable用のCSSを適用させる

### ISSUE THREAD

**Issue by gogotea55t** [piesmist/bbp-original-db-front#4]
Bootstrap自体はすでに読み込ませられているので、ページ内のTableタグの要素に適用させましょう。以下を参考に色々いじってみるといいかと思います。

* [公式マニュアル(英語)](https://getbootstrap.com/docs/4.4/content/tables/)
* [Bootstrapでテーブルを利用する方法](https://qiita.com/AquaMeria/items/b94d1d9ba074f04336b9)

**Comment by piesmist** [comment]
出来たわ・・・・・天才だわ俺・・・・・・

**Comment by gogotea55t** [comment]
OKでーす！完璧なのでこれは終了扱いにします。
